### PR TITLE
Fix help text and getting started URL

### LINKED ISSUE #583: airplane tasks -h shows wrong example
```
$ airplane -v
Version: 0.3.25 (2022-08-11T14:29:27Z)

$ airplane tasks -h
Manage tasks

Usage:
  airplane tasks [flags]

Commands:
  deploy     Deploy a task
  dev        Locally run a task
  execute    Execute a task
  get        Get information about a task
  init       Initialize a task definition
  list       Lists all tasks
  open       Opens a task page in browser

Flags:
  -h, --help   help for tasks


Examples:
  airplane tasks init
  airplane tasks deploy -f mytask.yml
  airplane tasks get my_task
  airplane tasks execute my_task

```
Please note that `airplane tasks deploy` does not have an `-f` switch.

### PR DESCRIPTION
**Pull request by joshma**
- Fixes #583 - updates help text
- Updates getting started URL based on new docs

### CODE REVIEW

**Review by ameyakhare — APPROVED** [review]

File: cmd/airplane/tasks/list/list.go [hunk 1]
```diff
@@ -54,7 +54,7 @@ func run(ctx context.Context, cfg config) error {
 		logger.Log(heredoc.Doc(`
 			There are no tasks yet.
 
-			To get started, follow our quickstart guide: https://docs.airplane.dev/getting-started/quickstart-guide
+			Check out the getting started guide: https://docs.airplane.dev/getting-started/overview
```
Comment (ameyakhare) [inline cmd/airplane/tasks/list/list.go:57]: maybe link to the "Build a task with code" docs instead of "Airplane concepts"
